---
title: "Meta_summary_stats"
output: html_document
date: "2023-11-13"
editor_options: 
  chunk_output_type: console
---

The purpose of this script is to investigate the structure and makeup of the data that we have from the studies that are included. I want to spit out histograms that will show how much of each study design we have, how many fall into different climates and time since fire buckets


```{r Load packages}
#for Jake/mac

rm(list=ls(all=T)) #this clears your Environment

library(ggplot2)
library(googlesheets4)
library(tidyverse)
library(lubridate)
library(ggpubr)
library(here)
library(corrplot)
library(PerformanceAnalytics)
library(Hmisc)
library(GGally)
```

#### NHD Catchment characteristics ####
```{r}
geospatial_data<- read_csv(here("Output_for_analysis", "06_Meta_geospatial_extraction_with_comids", "Geospatial_data_2024-02-15.csv"))

geospatial_data <- geospatial_data %>%
  mutate(Site = str_replace_all(Site, "_", " "))

```


```{r filtered data}
final_dataset <- read_csv(here("Output_for_analysis", "07_Meta_effect_size_models", "effect_size_geospatial_fire_lat_long.csv"))

# might want to include maxelevraw from the geospatial 
# stream order - probably sample in the more accessible portion of the catchment 
# stream order and effect size - in the bigger streams
# smaller stream - the bigger effect for nitrate, in bigger systems we are seeing a dilution of the impact. Stream order and watershed area are redundant because they can be used for a proxy for each other. 
# we want to choose area over stream order that is more informative. 
# add in maxelevraw for the correlation matrix.

```

```{r - plotting}
### TSF ####
ggplot(final_dataset, aes(x = Time_Since_Fire, fill = Time_Since_Fire)) +
  geom_bar() +
  xlab("Time Since Fire") +
  ylab("Frequency") +
  theme_bw() +
  theme(legend.position = "none")

### stream order  ####
ggplot(final_dataset, aes(x = streamorde, fill = streamorde)) +
  geom_bar() +
  xlab("Stream Order") +
  ylab("Frequency") +
  theme_bw() +
  theme(legend.position = "none")

### burn percentage ####
ggplot(final_dataset, aes(x = burn_percentage)) + 
  geom_histogram(binwidth = 10) +
  xlab("Burn Percentage") +
  ylab("Frequency") +
  theme_bw()

### Slope ####
ggplot(final_dataset, aes(x = slope)) + 
  geom_histogram(binwidth = 0.01) +
  xlab("Slope") +
  ylab("Frequency") +
  theme_bw()

### watershed area ####
ggplot(final_dataset, aes(x = totdasqkm)) + 
  geom_histogram(binwidth = 50) +
  xlab("Watershed Area") +
  ylab("Frequency") +
  theme_bw()
```

```{r - how many studies}
unique(final_dataset$Study_ID) # 18
```

```{r - correlation matrix - catchment characteristics}
### DOC #### 
final_dataset <- final_dataset %>% 
  mutate(Time_Since_Fire = as.numeric(Time_Since_Fire)) %>% 
  mutate(Time_Since_Fire = case_when(Study_ID == "Abbott et al. 2021" ~ 10,
                                     Study_ID == "Rhea et al. 2021" ~ 15,
                                     TRUE ~ Time_Since_Fire)) # changing the time since fire to a numeric structure and changing the abbott and rhea time since fire to the exact time since fire 
doc <- final_dataset %>% 
  filter(response_var == "DOC_Interp") %>% # filtering out DOC 
  dplyr::select(Study_ID, Site, Effect_size, Climate, burn_percentage, Time_Since_Fire) # Only want to do the catchment characteristics
  
doc <- doc %>%
  filter(!is.na(Site)) # Filter out Rhea and Abbott

doc <- doc %>% 
  filter(!Study_ID == "Hickenbottom et al. 2023") # Hickenbottom doesn't have catchment data because its too new

doc <- doc %>% 
  filter(!Study_ID == "Burd et al 2018") # Burd is in canada so it doesn't have catchment data 

doc_test <- left_join(doc, geospatial_data, by = "Site")
# doc_test <- left_join(doc, geospatial_data, by = c("Site", "totdasqkm", "minelevraw", "maxelevsmo", "minelevsmo",
#                                                    "elevfixed", "slope"))

doc_test <- doc_test %>% 
  dplyr::select(Study_ID, Site, Effect_size, Climate, totdasqkm, minelevraw, maxelevsmo, minelevsmo, elevfixed, slope, burn_percentage, Time_Since_Fire)
  

write_csv(doc, here("Output_for_analysis", "08_Meta_summary_stats", "doc_meta_random_forest.csv"))

  
# Simple correlation matrix between effect size and all the other catchment characteristics
doc <- doc %>% 
  select(Effect_size, totdasqkm, minelevraw, maxelevsmo, minelevsmo, elevfixed, slope, burn_percentage, Time_Since_Fire)

res <- cor(doc)
round(res, 2) 


# Correlation matrix with significance levels (p-value)
res2 <- rcorr(as.matrix(doc))
res2 # the only significant p-value with effect size is watershed area



corrplot(res, type = "upper", order = "FPC", 
         tl.col = "black", tl.srt = 45)


corrplot(res2$r, type="upper", order="hclust", 
         p.mat = res2$P, sig.level = 0.05, insig = "blank")

ggpairs(doc, columns = c("Effect_size", "totdasqkm", "minelevraw", "maxelevsmo","minelevsmo", "elevfixed", "slope", "burn_percentage", "Time_Since_Fire")) +
  theme_bw()


### NO3 #### 
no3 <- final_dataset %>% 
  filter(response_var == "NO3_Interp") %>% 
  dplyr::select(Effect_size, Climate, totdasqkm, minelevraw, maxelevsmo, minelevsmo, elevfixed, slope, burn_percentage, Time_Since_Fire) %>% 
  na.omit()

write_csv(no3, here("Output_for_analysis", "08_Meta_summary_stats", "no3_meta_random_forest.csv"))

ggpairs(no3, columns = c("Effect_size", "totdasqkm", "minelevraw", "maxelevsmo","minelevsmo", "elevfixed", "slope", "burn_percentage", "Time_Since_Fire")) +
  theme_bw()

# Correlation matrix with significance levels (p-value)
res <- cor(no3)
round(res, 2) 

res2 <- rcorr(as.matrix(no3))
res2 # the only significant p-value with effect size is watershed area



corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)



```


```{r ratio between burned and unburned watersheds}
library(tidyverse)
library(hrbrthemes)
watershed_area <- read_csv(here("inputs", "Studies_Summary", "Watershed_area.csv")) 

burn_ratio <- watershed_area %>%
  group_by(Study) %>%
  summarise(BR = sum(Watershed_Size_km[Burn_Unburn == "Burn"]) / sum(Watershed_Size_km[Burn_Unburn == "Unburn"]))

ggplot(burn_ratio, aes(x = BR)) +
  geom_histogram(binwidth = 1, fill = "#69b3a2", color = "#e9ecef", alpha = 0.9) +
  scale_x_continuous(breaks = seq(0, 40, by = 5), labels = seq(0, 40, by = 5)) +
  theme_bw() +
  ggtitle("Watershed Area (Burn) / Watershed Area (Unburn)")

ggsave("Watershed_Area_Burn_Ratio.pdf",
       path = here("initial_plots", "08_Meta_summary_stats"),
       width = 8, height = 6, units = "in")


```












