---
title: "Gerla_Galloway_percent_difference_test"
output: html_document
date: "2023-10-03"
editor_options: 
  chunk_output_type: console
---

The purpose of this script is to calculate the percent difference by concentration and by the load for one study to see how they differ. 
Gerla and Galloway have the most complete dataset to do this test 

## Load libraries 
```{r Jake/Mac}
#for Jake/mac

rm(list=ls(all=T)) #this clears your Environment

library(tidyverse)
library(readxl)
library(here)
library(ggplot2)

```

```{r - read in dataframes}
conc <- read_excel(here("inputs", "Studies", "Gerla_Galloway_1998", "Gerla_Galloway_1998.xlsx")) 

transport <- read_excel(here("inputs", "Studies", "Gerla_Galloway_1998", "Gerla_Galloway_1998_load.xlsx")) 

```


```{r calculations for concentrations}
MeanConcTest <- conc %>%
  group_by(Climate, NO3_unit, Time_Since_Fire) %>% 
  summarize(Ne = sum(Burn_Unburn == "Burn"),
                   Nc = sum(Burn_Unburn == "Unburn"),
                   Xe = mean(NO3[Burn_Unburn == "Burn"], na.rm = TRUE),
                   Xc = mean(NO3[Burn_Unburn == "Unburn"], na.rm = TRUE),
                   ES = log((Xe/Xc))) # taking the sum of observations for the unburn site and the burn site. It is also taking the mean of all of those observations

ggplot(conc, aes(x = Burn_Unburn, y = NO3, fill = Burn_Unburn)) +
  geom_boxplot() +
  scale_fill_manual(values=c("red3", "springgreen4")) +
  ggtitle("Concentration (mg_N_L)") +
  facet_wrap(~Time_Since_Fire, scales = "free") +
  theme_bw()

# calculating the percent change 
percent_change_conc <- MeanConcTest %>% 
  group_by(Climate, Time_Since_Fire) %>% 
  mutate(percent_change = (((Xe-Xc)/Xc)*100))

# Calculating the summary of all of the years
climate.summary <- percent_change_conc %>%
  group_by(Climate) %>%
  summarise(
    sd = sd(percent_change, na.rm = TRUE),
    percent_change = mean(percent_change))

climate.summary <- climate.summary %>% 
  mutate(Time_Since_Fire = 1)


# Plot percent difference 
ggplot(percent_change_conc, aes(percent_change, y = Climate, color = as.factor(Time_Since_Fire))) +
  geom_jitter(position = position_jitter(0.1), alpha = 0.4) +
  geom_pointrange(aes(xmin = percent_change-sd, xmax = percent_change + sd), data = climate.summary) +
  geom_vline(xintercept = 0, linewidth = 0.5, color = "red") +
  scale_color_brewer(palette = "Dark2",
                     guide = guide_legend(title = "Time Since Fire")) +
  xlab("Percent Change") +
  theme_bw()



# Testing out the Boerner way vs. the Dove way to see if Effect size is calculated the same way
Xe <- MeanConcTest$Xe
Xc <- MeanConcTest$Xc
Sd <- conc %>% 
  summarize(Sc = sd(NO3[Burn_Unburn == "Unburn"], na.rm = TRUE),
            St = sd(NO3[Burn_Unburn == "Burn"], na.rm = TRUE))
Sc <- Sd$Sc
St <- Sd$St
Nc <- MeanConcTest$Nc
Nt <- MeanConcTest$Ne

Sp <- sqrt(((Sc^2)*(Nc-1) + ((St^2)*(Nt-1)) / 
         ((Nt + Nc - 2))))

ES <- ((Xe - Xc)/
         (Sp)) # This yields 0.041 vs. Dove which yields 0.54


```


```{r calculations for transport}
MeanTransportTest <- transport %>%
  group_by(Climate, NO3_unit, Time_Since_Fire) %>% 
  summarize(Ne = sum(Burn_Unburn == "Burn"),
                   Nc = sum(Burn_Unburn == "Unburn"),
                   Xe = mean(NO3[Burn_Unburn == "Burn"], na.rm = TRUE),
                   Xc = mean(NO3[Burn_Unburn == "Unburn"], na.rm = TRUE),
                   ES = log((Xe/Xc))) # taking the sum of observations for the unburn site and the burn site. It is also taking the mean of all of those observations

ggplot(transport, aes(x = Burn_Unburn, y = NO3, fill = Burn_Unburn)) +
  geom_boxplot() +
  scale_fill_manual(values=c("red3", "springgreen4")) +
  ggtitle("Transport (mmol NO3_ha_s)") +
  facet_wrap(~ Time_Since_Fire, scales = "free") +
  theme_bw()

# calculating the percent change 
percent_change_transport <- MeanTransportTest %>% 
  group_by(Climate, Time_Since_Fire) %>% 
  mutate(percent_change = (((Xe-Xc)/Xc)*100))


# Calculating the summary of all of the years
transport.summary <- percent_change_transport %>%
  group_by(Climate) %>%
  summarise(
    sd = sd(percent_change, na.rm = TRUE),
    percent_change = mean(percent_change))

transport.summary <- transport.summary %>% 
  mutate(Time_Since_Fire = 1)


# Plot percent difference 
ggplot(percent_change_transport, aes(percent_change, y = Climate, color = as.factor(Time_Since_Fire))) +
  geom_jitter(position = position_jitter(0.1), alpha = 0.4) +
  geom_pointrange(aes(xmin = percent_change-sd, xmax = percent_change + sd), data = transport.summary) +
  geom_vline(xintercept = 0, linewidth = 0.5, color = "red") +
  scale_color_brewer(palette = "Dark2",
                     guide = guide_legend(title = "Time Since Fire")) +
  xlab("Percent Change") +
  theme_bw()

```

```{r merge}

combined_pc <- full_join(percent_change_conc, percent_change_transport)


combined_pc <- combined_pc %>% 
  mutate(Method = ifelse(NO3_unit == "mmol NO3_ha_s", "Yield", "Concentration"))

ggplot(combined_pc, aes(x = percent_change, y = Climate, color = Method)) +
  geom_point() +
  scale_color_manual(values = c("#00AFBB", "#E7B800"),
                     guide = guide_legend(title = "Method"),
                     labels = c('Transport (mmol NO3_ha_s)', 'Concentration (mg_N_L)')) +
  xlab("Percent Change") +
  facet_wrap(~Time_Since_Fire, scales = "free") +
  theme_bw()

```














