---
title: "Gerla_Galloway_temporal_normalization_test"
output: html_document
date: "2023-10-10"
---

## Load libraries 
```{r Jake/Mac}
#for Jake/mac

rm(list=ls(all=T)) #this clears your Environment

library(tidyverse)
library(readxl)
library(here)
library(ggplot2)
library(forecastML)
library(zoo)
```

```{r - read in dataframe}
gerla <- read_csv(here("inputs", "Studies", "Gerla_Galloway_1998", "Gerla_Galloway_1998.csv")) 

gerla <- gerla %>% 
  mutate(Sampling_Date = mdy(Sampling_Date))

gerla_burn <- gerla %>% 
  filter(Burn_Unburn == "Burn") # If I do the interpolate I am going to have to split this by burn and unburn so it doesnt interpolate burn data for an unburn dataset for example. 

gerla_unburn <- gerla %>% 
  filter(Burn_Unburn == "Unburn") # If I do the interpolate I am going to have to split this by burn and unburn so it doesnt interpolate burn data for an unburn dataset for example. 

ggplot(gerla_burn, aes(x = Sampling_Date, y = NO3)) +
  geom_point() +
  theme_bw()

```

```{r calculations for burn monthly concentrations}
gerla_burn_fill <- fill_gaps(gerla_burn, date_col = 11, '1 day') %>% 
  mutate(year = year(Sampling_Date),
         month = month(Sampling_Date),
         day = day(Sampling_Date),
         NO3 = na.approx(NO3))   
# changing the format of the sampling date column and then separating year month and day 
# interpolating each day within the time series 
  
ggplot(gerla_burn_fill, aes(x = Sampling_Date, y = NO3)) +
  geom_point() +
  theme_bw()

gerla_burn_fill_max <- fill_gaps(gerla_burn, date_col = 11, '1 day') %>% 
  mutate(year = year(Sampling_Date),
         month = month(Sampling_Date),
         day = day(Sampling_Date),
         NO3 = na.approx(NO3, maxgap = 50))  

ggplot(gerla_burn_fill_max, aes(x = Sampling_Date, y = NO3)) +
  geom_point() +
  theme_bw()

gerla_burn_fill <- gerla_burn_fill %>%
  fill(Study_ID:Mean_Median_or_IndividualSample) # fill in the rows that were created from the na.approximate function

# Taking the mean concentrations by month for the burned and the unburned sites
gerla_month_mean_burn <- gerla_burn_fill %>%
  group_by(Climate, year, month) %>%
  summarize(Xe = mean(NO3[Burn_Unburn == "Burn"], na.rm = TRUE),
            TimeNorm_Burn = Xe * 6423/100)

```

```{r calculations for unburn monthly concentrations}
gerla_unburn_fill <- fill_gaps(gerla_unburn, date_col = 11, '1 day') %>% 
  mutate(year = year(Sampling_Date),
         month = month(Sampling_Date),
         day = day(Sampling_Date),
         NO3 = na.approx(NO3))   
# changing the format of the sampling date column and then separating year month and day 
# interpolating each day within the time series 
  
ggplot(gerla_unburn_fill, aes(x = Sampling_Date, y = NO3)) +
  geom_point() +
  theme_bw()

gerla_unburn_fill <- gerla_unburn_fill %>%
  fill(Study_ID:Mean_Median_or_IndividualSample) # fill in the rows that were created from the na.approximate function

# Taking the mean concentrations by month for the burned and the unburned sites
gerla_month_mean_unburn <- gerla_unburn_fill %>%
  group_by(Climate, year, month) %>%
  summarize(Xc = mean(NO3[Burn_Unburn == "Unburn"], na.rm = TRUE),
            TimeNorm_Unburn = Xc * 4946/100)

```

```{r merge burn and unburn}

gerla_combined <- full_join(gerla_month_mean_burn, gerla_month_mean_unburn)

ggplot(gerla_combined, aes(x = TimeNorm_Burn, y = TimeNorm_Unburn, color = as.factor(month))) +
  geom_point() +
  facet_wrap(~year, scales = "free") +
  theme_bw()

```


```{r percent_change}
# Taking the mean concentrations by month for the burned and the unburned sites 
# gerla_month_mean <- gerla %>%
#   group_by(Climate, NO3_unit, month) %>% 
#   summarize(Xe = mean(NO3[Burn_Unburn == "Burn"], na.rm = TRUE),
#             Xc = mean(NO3[Burn_Unburn == "Unburn"], na.rm = TRUE), 
#             TimeNorm_Burn = Xe * 6423/100, 
#             TimeNorm_Unburn = Xc * 4946/100, 
#             percent_change = (((TimeNorm_Burn-TimeNorm_Unburn)/TimeNorm_Unburn)*100))

# Other ways to calculate percent_change #
# gerla_month_mean_two <- gerla %>% 
#   group_by(Burn_Unburn, month, Area_watershed) %>% 
#   summarize(conc = mean(NO3))
# 
# gerla_time_norm <- gerla_month_mean_two %>% 
#   summarise(TimeNorm = conc * (Area_watershed/100))
# 
# # calculating the percent change 
# percent_change_transport <- MeanTransportTest %>% 
#   group_by(Climate, Time_Since_Fire) %>% 
#   mutate(percent_change = (((Xe-Xc)/Xc)*100))



```

```{r plot}
# ggplot(gerla_month_mean, aes(x = percent_change, y = Climate, color = as.factor(month))) +
#   geom_jitter() +
#   scale_color_brewer(palette = "Dark2",
#                      guide = guide_legend(title = "Method")) +
#   xlab("Percent Change") +
#   theme_bw()

#

```




















